<?php

/**
 * @file
 * Musica module.
 */

/**
 * Implements hook_theme().
 *
 * @see https://www.drupal.org/docs/develop/theming-drupal/twig-in-drupal/create-custom-twig-templates-for-custom-module
 * @see https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Render%21theme.api.php/function/hook_theme/8.2.x
 */
function musica_theme($existing, $type, $theme, $path): array {
  return [
    'artist' => [
      'variables' => [
        'name' => '',
        'state' => NULL,
      ],
    ],
  ];
}
