version: '3.9'

services:
  swagger:
    image: swaggerapi/swagger-ui
    restart: always
    env_file:
      - secrets.env
    ports:
      - 8080:8080
    environment:
      # https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md#docker
      SUPPORTED_SUBMIT_METHODS: "['get', 'put', 'post', 'delete', 'options', 'head', 'patch', 'trace']"
      DISPLAY_OPERATION_ID: true
      DEEP_LINKING: true
      TRY_IT_OUT_ENABLED: true
      PERSIST_AUTHORIZATION: true
      SHOW_EXTENSIONS: true
      FILTER: true
      DOC_EXPANSION: none
      OAUTH2_REDIRECT_URL: ""
      CONFIG_URL: ./swagger-config.json
      # See https://swagger.io/docs/open-source-tools/swagger-ui/usage/oauth2/
      OAUTH_CLIENT_ID: ${OAUTH_CLIENT_ID}
      OAUTH_CLIENT_SECRET: ${OAUTH_CLIENT_SECRET}
      OAUTH_APP_NAME: Bakari Desktop Non-Commercial
      OAUTH_SCOPE_SEPARATOR: " "
      # OAUTH_SCOPES: "['user-read-playback-state', 'user-modify-playback-state', 'user-read-currently-playing', 'app-remote-control', 'streaming', 'playlist-read-private', 'playlist-read-collaborative', 'playlist-modify-private', 'playlist-modify-public', 'user-read-playback-position', 'user-top-read', 'user-read-recently-played', 'user-library-modify', 'user-library-read']"
      # OAUTH_USE_PKCE: true
    volumes:
      # Spotify schema gives CORS issues, must copy manually.
      - ./spotify-open-api-schema.yaml:/usr/share/nginx/html/spotify-open-api-schema.yaml
      # Downloaded to local for oauth modifications
      # https://raw.githubusercontent.com/sonallux/spotify-web-api/main/fixed-spotify-open-api.yml
      - ./sonallux-spotify-open-api.yml:/usr/share/nginx/html/sonallux-spotify-open-api.yml
      - ./swagger-config.json:/usr/share/nginx/html/swagger-config.json
