# Schema generator instructions
#
# Execute with:
#
# vendor/bin/schema generate \
# web/modules/custom/musica/src/API/Spotify \
# web/modules/custom/musica/src/API/config/spotify-schema.yaml --verbose --no-interaction
#
# Then to get a clean bill of health from PHPCS, run:
# vendor/bin/php-cs-fixer fix web/modules/custom/musica/src/API/Spotify
#

# api/config/schema.yaml
# See https://api-platform.com/docs/schema-generator/getting-started/
# https://api-platform.com/docs/schema-generator/configuration/
openApi:
  file: 'sonallux-spotify-open-api-spec.yml'

# vendor/bin/schema generate api/src/ api/config/schema.yaml -vv
# docker compose exec php \
#    vendor/bin/schema generate src/ config/schema.yaml -vv

namespaces:
  entity: Drupal\musica\API\Spotify\Entity
  enum: Drupal\musica\API\Spotify\Enum
  interface: Drupal\musica\API\Spotify\Interface

fieldVisibility: public
accessorMethods: false

# Enable/disable Doctrine Collections.
# Default is TRUE.
# See https://www.doctrine-project.org/projects/doctrine-collections/en/stable/index.html
doctrine:
  useCollection: true

# See:
# - https://lov.linkeddata.es/dataset/lov/terms?q=music
# - http://musicontology.com/specification/#term-MusicArtist
# - http://musicontology.com/
#

vocabularies:
  - { uri: 'https://schema.org/version/latest/schemaorg-current-https.rdf', format: null, allTypes: false }
  # - { uri: 'https://raw.githubusercontent.com/motools/musicontology/master/rdf/musicontology.rdfs', format: null, allTypes: false }
  #- { uri: 'https://raw.githubusercontent.com/metabrainz/mmd-schema/master/schema/musicbrainz_mmd-2.0.rngf', format: null, allTypes: false }
  #- https://raw.githubusercontent.com/OntologyAnthology/BBC/main/creativework.rdf

allTypes: false # Generate all types by default for vocabularies
resolveTypes: true # Resolve types in other vocabularies

# types:
#   Albums:
#     vocabularyNamespace: http://purl.org/ontology/mo/album
#   Artists:
#     vocabularyNamespace: http://purl.org/ontology/mo/MusicArtist
#   Audiobooks:
#     vocabularyNamespace: http://purl.org/ontology/mo/audiobook
#   Categories:
#     vocabularyNamespace: https://www.bbc.co.uk/ontologies/creativework/tag
#   # Chapters:
#   #   vocabularyNamespace: http://purl.org/ontology/mo/album
#   # Episodes:
#   #   vocabularyNamespace: http://purl.org/ontology/mo/album
#   # Library:
#   #   vocabularyNamespace: http://purl.org/ontology/mo/album
#   Genres:
#     vocabularyNamespace: http://purl.org/ontology/mo/Genre
#   # Markets:
#   #   vocabularyNamespace: http://purl.org/ontology/mo/album
#   # Player:
#   #   vocabularyNamespace: http://purl.org/ontology/mo/album
#   # Playlists:
#   #   vocabularyNamespace: http://purl.org/ontology/mo/album
#   # Search:
#   #   vocabularyNamespace: http://purl.org/ontology/mo/album
#   Shows:
#     vocabularyNamespace: http://purl.org/ontology/mo/Show
#   Tracks:
#     vocabularyNamespace: http://purl.org/ontology/mo/Track
#   Users:
#     vocabularyNamespace: http://xmlns.com/foaf/0.1/#term_OnlineAccount

header: |
  /**
  * @file
  * Data Transfer Object for Spotify Web API.
  *
  * @see https://api-platform.com/docs/schema-generator/
  * @phpcs:disable Drupal.Classes.FullyQualifiedNamespace.UseStatementMissing,Drupal.Commenting.DataTypeNamespace.DataTypeNamespace,Drupal.Commenting.DocComment.ShortSingleLine
  */
