<?php

/**
 * @file
 * The module file.
 */

/**
 * Implements hook_views_data().
 *
 * Gets called when going to admin/structure/views/add.
 */
function musica_views_views_data() {
  $data['musica_views_remote_data']['table']['group'] = 'musica_views_remote_data';
  $data['musica_views_remote_data']['table']['base'] = [
    'title' => 'Musica API',
    'query_id' => 'views_remote_data_query',
  ];

  return $data;
}

/**
 * Implements hook_theme().
 */
function musica_views_theme($existing, $type, $theme, $path) {
  return [
    'views_view_field__property' => [
      // 'template' => 'views-view-field--my-field-name',
      'template' => 'views-view-field--property',
      'base hook' => 'views_view_field',
    ],

    // Views templates.
    // 'views_view__my_views_block' => [
    //   'template' => 'views-view--my-views-id',
    //   'base hook' => 'views_view',
    // ],
    // // Views unformatted templates.
    // 'views_view_unformatted__my_views_block' => [
    //   'template' => 'views-view-unformatted--my-views-id',
    //   'base hook' => 'views_view_unformatted',
    // ],
  ];
}
