<?php

/**
 * @file
 * The module file.
 */

/**
 * Implements hook_views_data().
 *
 * Gets called when going to admin/structure/views/add.
 */
function musica_views_views_data() {
  $data['musica_views_remote_data']['table']['group'] = 'musica_views_remote_data';
  $data['musica_views_remote_data']['table']['base'] = [
    'title' => 'Musica API',
    'query_id' => 'views_remote_data_query',
  ];

  return $data;
}
