#!/usr/bin/env bash

# ========= WSL TEST RUNNER =========
# TEST RUNNER FOR PHPUNIT VERSION 10.x
# ========= WSL TEST RUNNER =========
#
# Rules:
# - Invoked from docroot, or from web root.
# - Expects core vendor to be installed
# - Expects drupal/core-dev to be present, which includes PHPUnit in core vendor.
# - Kernel and integration dependencies (env vars, services, etc) shall be
#   available, as usual, when running those kind of tests.
#

echo "Your current work directory is $PWD"

# Variables by integration tests.
export SIMPLETEST_BASE_URL="https://d10ee.lndo.site"
export SIMPLETEST_DB="mysql://drupalX:drupalX@127.0.0.1:53846/drupal10_simpletest"
export BROWSERTEST_OUTPUT_DIRECTORY="web/sites/simpletest/browser_output"
export BROWSERTEST_OUTPUT_BASE_URL=""

mkdir -p $BROWSERTEST_OUTPUT_DIRECTORY

# https://www.drupal.org/project/dbal/issues/3246773
export SIMPLETEST_DB="sqlite://localhost/:memory:"
export SYMFONY_DEPRECATIONS_HELPER="disabled"


# See https://docs.phpunit.de/en/9.6/textui.html#command-line-options
# Bootstrap and configs are requiring absolute paths inside Docker/Lando.

# 5:15 5/11 Confirmed outside binary fully runs kernel test (inside docker).
# php vendor/bin/phpunit \

# Sauce environment variables for application.
source ./musica.env
echo $soundcloud_client_id
echo $soundcloud_client_secret


# PHPUnit requires the "ctype", "dom", "json", "libxml", "mbstring", "tokenizer", "xml", "xmlwriter" extensions, but the "ctype" extension is not available.

# php vendor/bin/phpunit \

# kernel+ tests causing coverage to hang.

truncate -s 0 log.txt

# Tailing logs show execution completed but not for reports, they just hang.
# tail -F log.txt

#   -d pcov.enabled=1 -d pcov.directory=web/modules/contrib/musica/src -d pcov.exclude="~vendor~" \

php ./phpunit \
  --bootstrap web/core/tests/bootstrap.php \
  --configuration web/core/phpunit.xml.dist \
  --exclude-group ignore \
  --group target3 \
  --stop-on-defect \
  --cache-result \
  --display-errors \
  --no-coverage \
  --testdox \
  --log-events-verbose-text log.txt \
  web/modules/contrib/musica/tests

# --do-not-cache-result \
# --coverage-cobertura $PWD/coverage.cobertura.xml \
# --no-coverage \
# https://dev.to/swashata/setup-php-pcov-for-5-times-faster-phpunit-code-coverage-3d9c
# curl -o phpunit https://phar.phpunit.de/phpunit-10.5.20.phar
