#!/usr/bin/env bash

# ========= WSL TEST RUNNER =========
# TEST RUNNER FOR PHPUNIT VERSION 10.x
# ========= WSL TEST RUNNER =========
#
# Rules:
# - Invoked from docroot, or from web root.
# - Expects core vendor to be installed
# - Expects drupal/core-dev to be present, which includes PHPUnit in core vendor.
# - Kernel and integration dependencies (env vars, services, etc) shall be
#   available, as usual, when running those kind of tests.
#

echo "Your current work directory is $PWD"

# Variables by integration tests.
export SIMPLETEST_BASE_URL="https://d10ee.lndo.site"
# export SIMPLETEST_DB="mysql://drupalX:drupalX@127.0.0.1:53846/drupal10_simpletest"
export BROWSERTEST_OUTPUT_DIRECTORY="web/sites/simpletest/browser_output"
export BROWSERTEST_OUTPUT_BASE_URL=""

mkdir -p $BROWSERTEST_OUTPUT_DIRECTORY

# https://www.drupal.org/project/dbal/issues/3246773
export SIMPLETEST_DB="sqlite://localhost/:memory:"
export SYMFONY_DEPRECATIONS_HELPER="disabled"

# Sauce environment variables for application.
source ./musica.env
echo $soundcloud_client_id
echo $soundcloud_client_secret

# https://xdebug.org/docs/code_coverage#mode
# export XDEBUG_MODE="coverage,develop"

# Tailing logs show execution completed but not for reports, they just hang.
# tail -F log.txt
truncate -s 0 log.txt

# COVERAGE HANG 6/25/2024
# Including web/core/phpunit.xml.dist hangs coverage, core bootstrap is fine.
# Unit can be done without core config in order to have coverage.

php vendor/bin/phpunit \
  --bootstrap web/core/tests/bootstrap.php \
  --testdox \
  --exclude-group ignore \
  --group group10 \
  --stop-on-defect \
  --display-errors \
  --cache-result \
  \
  --coverage-text \
  --coverage-cobertura web/modules/contrib/musica/coverage.cobertura.xml \
  --log-junit $PWD/junit.xml \
  --coverage-filter web/modules/contrib/musica/src \
  \
  web/modules/contrib/musica/tests

#   --log-events-verbose-text log.txt \
# --bootstrap web/core/tests/bootstrap.php \
#   --configuration web/core/phpunit.xml.dist \
# --debug
# --do-not-cache-result \
# --coverage-cobertura $PWD/coverage.cobertura.xml \
# --no-coverage \
# curl -o phpunit https://phar.phpunit.de/phpunit-10.5.20.phar
