#!/usr/bin/env bash

# ========= WSL TEST RUNNER =========
# TEST RUNNER FOR PHPUNIT VERSION 10.x
# ========= WSL TEST RUNNER =========
#
# Rules:
# - Invoked from docroot, or from web root.
# - Expects core vendor to be installed
# - Expects drupal/core-dev to be present, which includes PHPUnit in core vendor.
# - Kernel and integration dependencies (env vars, services, etc) shall be
#   available, as usual, when running those kind of tests.
#



# Enable debugging.
export XDEBUG_MODE="debug,coverage"
export XDEBUG_CONFIG="idekey=VSCODE"
# export XDEBUG_MODE=coverage


source ./test
