musica.settings:
  type: config_object
  mapping:
  spotify_api_endpoint:
    type: string
    label: 'Spotify API Endpoint'
  spotify_client_id:
    type: string
    label: 'Spotify API Client ID'
  spotify_client_secret:
    type: string
    label: 'Spotify API Client Secret'
  spotify_redirect_url:
    type: string
    label: 'Spotify Authorization Redirect URL'
